<a href="https://colab.research.google.com/github/Vaibhav67979/MachineLearning/blob/main/MLCourse/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 

NumPy package is an ndarray object.
This encapsulates n-dimensional arrays of homogenous data types.
- Numpy arrays are of fixed size. 
- Changing the size of of an ndarrray will create a new array and delete the old one.
- All elements pf the numpy array should be of a same data type.

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use.

Numpy is faster because of vectorization.
- vectorized code is more concise and easier to read
- fewer lines of code generally means fewer bugs
- the code more closely resembles standard mathematical notation


## Installation 


In [ ]:
pip install numpy
""" or """
conda install numpy
""" if on jupyter notebook use an exclamation mark """
!pip install numpy

## Importing NumPy

In [ ]:
import numpy as np

## Creating an array


In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Basic functions

In [ ]:
a.shape

(4, 5)

In [ ]:
a.size

20

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a.data

In [ ]:
b = np.array([2,3,4,True,"Hello",2.3444])
b.dtype

dtype('<U32')

In [ ]:
c = np.array([(1,2,3),(4,5,6)])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d = np.array([[1,2],[3,4]],dtype = complex)
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((1,2,3,4,5),dtype= int)

array([[[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]]])

In [ ]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
np.arange(0,2,0.3)


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
np.arange(1000000000,9000000000000,885452888987)

array([   1000000000,  886452888987, 1771905777974, 2657358666961,
       3542811555948, 4428264444935, 5313717333922, 6199170222909,
       7084623111896, 7970076000883, 8855528889870])

In [ ]:
np.linspace(0,2,10)# last argument in the number of elements we want

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

## Arithmetic operations

In [ ]:
a = np.linspace(2,18,9).reshape(3,3)
print(a)
b = np.linspace(3,27,9).reshape(3,3)
print(b)
print(a+b)
print(a*b) # element wise product
print(a/b)
print(a-b)
print(a%b)

# matrix product or dot product

print(a@b) 
a.dot(b)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]
[[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]]
[[  6.  24.  54.]
 [ 96. 150. 216.]
 [294. 384. 486.]]
[[0.66666667 0.66666667 0.66666667]
 [0.66666667 0.66666667 0.66666667]
 [0.66666667 0.66666667 0.66666667]]
[[-1. -2. -3.]
 [-4. -5. -6.]
 [-7. -8. -9.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[180. 216. 252.]
 [396. 486. 576.]
 [612. 756. 900.]]


array([[180., 216., 252.],
       [396., 486., 576.],
       [612., 756., 900.]])

In [ ]:
10*np.sin(a)

array([[ 9.09297427, -7.56802495, -2.79415498],
       [ 9.89358247, -5.44021111, -5.36572918],
       [ 9.90607356, -2.87903317, -7.50987247]])

In [ ]:
a<3

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
rg = np.random.default_rng(1)
a = np.ones((2,3),dtype = int)
print(a)
b = rg.random((2,3))
print(b)
# a *= 3
# print(a)
# # b += a # each element of matrix b is added with each element of matrix a
# # print(b)
# b *= a # each element of matrix b is getting multiplied by each element of matrix a
# print(b)

[[1 1 1]
 [1 1 1]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
[[3 3 3]
 [3 3 3]]
[[1.53546487 2.85139109 0.43247884]
 [2.84594834 0.93549436 1.26997935]]


### random number generator

In [ ]:
""" Random number generator between 0 - 100 """
c = rg.random((2,3))
print(c)

c = c*50 + 50
print(c)

""" or """
# print(50 + c*50)



[[0.84558557 0.27327852 0.28590552]
 [0.2016326  0.76513804 0.1435602 ]]
[[92.27927858 63.66392585 64.29527579]
 [60.08162996 88.25690203 57.1780102 ]]


' or '

In [ ]:
c.sum()

505.2066783968192

In [ ]:
c.min()

62.76415994804137

In [ ]:
c.max()

97.2951791890383

In [ ]:
d = rg.random((30,30))
d = d*50 + 50
d = d.astype(int)
d

array([[67, 80, 95, 95, 92, 82, 80, 85, 70, 87, 51, 96, 85, 50, 85, 78,
        80, 82, 56, 52, 60, 54, 60, 86, 66, 78, 62, 93, 53, 77],
       [77, 89, 94, 87, 55, 88, 73, 62, 88, 89, 74, 91, 91, 88, 84, 78,
        75, 73, 69, 65, 59, 55, 56, 95, 95, 73, 96, 91, 73, 97],
       [66, 79, 98, 61, 91, 68, 68, 91, 65, 69, 72, 63, 50, 99, 50, 73,
        78, 75, 70, 51, 82, 52, 67, 54, 73, 98, 61, 74, 75, 99],
       [90, 76, 73, 98, 99, 93, 89, 91, 99, 89, 53, 52, 95, 92, 79, 91,
        97, 77, 90, 74, 68, 69, 61, 56, 97, 60, 94, 59, 58, 70],
       [89, 61, 52, 96, 97, 70, 74, 85, 86, 82, 82, 76, 64, 61, 89, 80,
        84, 62, 99, 81, 50, 81, 59, 66, 70, 52, 51, 73, 86, 75],
       [59, 52, 80, 80, 58, 77, 86, 99, 93, 55, 53, 64, 90, 95, 97, 60,
        76, 60, 72, 87, 92, 72, 78, 79, 97, 64, 87, 85, 74, 55],
       [87, 94, 80, 69, 95, 65, 99, 94, 70, 50, 76, 50, 74, 82, 92, 50,
        67, 68, 79, 64, 85, 80, 71, 73, 50, 59, 99, 66, 67, 75],
       [85, 97, 56, 79, 66, 54, 67, 82, 5

100 digit random prime integer

In [ ]:
import random

def is_prime(n, k=10):
    # Implement the Miller-Rabin primality test
    if n == 2 or n == 3:
        return True
    if n <= 1 or n % 2 == 0:
        return False

    r, d = 0, n - 1
    while d % 2 == 0:
        r += 1
        d //= 2

    for _ in range(k):
        a = random.randint(2, n - 2)
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue

        for _ in range(r - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False

    return True

# Generate a random 100-digit number
n = random.randint(10**99, 10**100)

# Keep generating random numbers until we find a prime
while not is_prime(n):
    n = random.randint(10**99, 10**100)

print(n)



5598185678216414715196631843330798250850675046784244185404291092251678598026499191193687452321974303


100 digit random number generator

In [ ]:
import numpy as np

# Generate a random float between 0 and 1
rand_float = np.random.random_sample()

# Convert the float to an integer and store it as a string
rand_int_str = str(int(rand_float * 10**100))

# Extract the first 100 digits of the string
rand_100_digits = rand_int_str[:100]

print(rand_100_digits)

6806048056300127911285449220497065586255547316019301664343041066411402542233759910392718042920386560


In [ ]:
N = np.random.rand()

n = int(N * 10**100)

print(n)

9421499406106715404775065174453639182010125691832630918973760963429730613784600126095889855351357440


## Random Numbers

- Pseudo random numbers (from code)
- True random numbers (from real life) (ex : data from a sensor)

### Random float between 0 to 1

multiply to set the lower range 
add to modify the upper range

In [ ]:
x = np.random.random()
print(x)
y = np.random.rand()
print(y)

0.6353369951848805
0.8160379437699341


### random integer between a given range

In [ ]:
x = np.random.randint(0,10)
print(x)

3


### Generate random integer between 0 to 100

In [ ]:
x = np.random.randint(100)
x

44

### 100 random numbers between 0 to 1

In [ ]:
x = np.random.rand(100)
x

array([0.78377729, 0.05147445, 0.93654025, 0.98464109, 0.5450338 ,
       0.42189474, 0.5356724 , 0.57013285, 0.04079467, 0.95661357,
       0.46689647, 0.57641068, 0.13517709, 0.18763361, 0.34835707,
       0.89731195, 0.56983651, 0.88388981, 0.19630523, 0.25170131,
       0.40955292, 0.08063449, 0.61331152, 0.43945272, 0.72310979,
       0.24507005, 0.99225467, 0.05559236, 0.29915885, 0.7977789 ,
       0.68969573, 0.93186897, 0.67146007, 0.4427951 , 0.86485997,
       0.62594034, 0.905644  , 0.23433043, 0.08421963, 0.36266149,
       0.65456886, 0.80272147, 0.70049888, 0.84256992, 0.28018083,
       0.50814257, 0.78658847, 0.75452645, 0.07747894, 0.71490215,
       0.60978769, 0.81702668, 0.68518073, 0.73784116, 0.67998538,
       0.60924069, 0.22399359, 0.61258432, 0.58813288, 0.31413506,
       0.36610206, 0.60049027, 0.49253956, 0.06147094, 0.1358661 ,
       0.49333399, 0.93846989, 0.61167366, 0.7136913 , 0.87586467,
       0.78018598, 0.50552029, 0.74944342, 0.47923271, 0.52030

### Random choice

In [ ]:
x = np.random.choice([3,5,6,7,8])
x

6

In [ ]:
b = ['hi', 'hello', 'hola', 'ni hao', 'namaste']
x = np.random.choice(b)
x

'hello'

In [ ]:
x = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[7 9 7 7 3]
 [3 7 9 7 9]
 [5 3 3 3 7]]


## Ufunc

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:
- where = boolean array or condition defining where the operations should take place.
- dtype = defining the return type of elements.
- out = output array where the return value should be copied.

### Creating your own ufunc

To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:
1. function - the name of the function.
2. inputs - the number of input arguments (arrays).
3. outputs - the number of output arrays.

In [ ]:
import numpy as np

def add(x, y):
  return x+y

myadd = np.frompyfunc(add, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


To test if the function is a ufunc use - 

In [ ]:
print(type(myadd))
print(type(add))

<class 'numpy.ufunc'>
<class 'function'>


In [ ]:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

if type(myadd) == np.ufunc:
  print('myadd is ufunc')
else:
  print('myadd is not ufunc')

add is ufunc
myadd is ufunc


### Simple arithmetic

add()

subtract()

multiply()

divide()

power()

mod() / remainder()

divmod() - both quotient and mod

absolute() / abs()

### Rounding Decimals

- truncation = trunc()
- fix = fix()
- rounding = around()
- floor = floor()
- ceil = ceil()